AWSTemplateFormatVersion: '2010-09-09'
Description: Photo Album Web Application Infrastructure

Resources:
  # S3 Bucket
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "assignment2-b1-frontend-cf"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  PhotosBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "assignment3-b2-photos-cf"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  # IAM Role for Lambda Functions
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: ['sts:AssumeRole']
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - 'logs:*'
                  - 's3:*'
                  - 'rekognition:*'
                  - 'lex:*'
                Resource: '*'


  # Lambda Functions
  IndexPhotosFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "assingment3-LF1-index-photos-2-cf"
      Runtime: "python3.12"
      Handler: "index.handler"
      Code:
        S3Bucket: "assignment3-lambda-codepipeline"
        S3Key: "LF1.zip"
      Role: !GetAtt LambdaExecutionRole.Arn

  SearchPhotosFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "assingment3-LF2-search-photos-2-cf"
      Runtime: "python3.12"
      Handler: "search.handler"
      Code:
        S3Bucket: "assignment3-lambda-codepipeline"
        S3Key: "LF2.zip"
      Role: !GetAtt LambdaExecutionRole.Arn

  # API Gateway
  PhotoAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: "PhotoAPI"
      Description: "API for photo album application"

  # /search resource
  SearchResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref PhotoAPI
      ParentId: !GetAtt PhotoAPI.RootResourceId
      PathPart: search

  # GET method on /search
  SearchGETMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref PhotoAPI
      ResourceId: !Ref SearchResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SearchPhotosFunction.Arn}/invocations"
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              application/json: ""
            ResponseParameters:
              method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: "Empty"
          ResponseParameters:
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Origin: true

  # OPTIONS method on /search
  SearchOPTIONSMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref PhotoAPI
      ResourceId: !Ref SearchResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SearchPhotosFunction.Arn}/invocations"
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              application/json: ""
            ResponseParameters:
              method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: "Empty"
          ResponseParameters:
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Origin: true

  # /upload resource
  UploadResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref PhotoAPI
      ParentId: !GetAtt PhotoAPI.RootResourceId
      PathPart: upload

  # /{key} resource
  ObjectResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref PhotoAPI
      ParentId: !Ref UploadResource
      PathPart: '{key}'

  # OPTIONS method on /{key}
  ObjectOPTIONSMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref PhotoAPI
      ResourceId: !Ref ObjectResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              application/json: ""
            ResponseParameters:
              method.response.header.Access-Control-Allow-Methods: "'PUT,OPTIONS'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,x-amz-meta-customLabels'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: "Empty"
          ResponseParameters:
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Origin: true
  
  # PUT method on /{key}
  ObjectPutMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref PhotoAPI
      ResourceId: !Ref ObjectResource
      HttpMethod: PUT
      AuthorizationType: NONE
      Integration:
        Type: AWS
        Uri: arn:aws:apigateway:us-east-1:s3:path/{bucket}/{key}
        IntegrationHttpMethod: PUT
        Credentials: arn:aws:iam::767397968615:role/service-role/assingment3-LF1-index-photos-role-lwvbof8w
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              application/json: ""
            ResponseParameters:
              method.response.header.Access-Control-Allow-Methods: "'PUT,OPTIONS'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,x-amz-meta-customLabels'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: "Empty"
          ResponseParameters:
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Origin: true

Outputs:
  FrontendBucketName:
    Value: !Ref FrontendBucket
  PhotoBucketName:
    Value: !Ref PhotosBucket
  IndexPhotosFunctionArn:
    Value: !GetAtt IndexPhotosFunction.Arn
  SearchPhotosFunctionArn:
    Value: !GetAtt SearchPhotosFunction.Arn
  AssignmentPhotoAPIUrl:
    Value: !Sub "https://${PhotoAPI}.execute-api.${AWS::Region}.amazonaws.com/dev-v1"