version: 0.2

phases:
  build:
    commands:
      - echo "frontend-buildspec has been called"

  post_build:
    commands:
      - echo "Pushing to S3"
      - aws s3 sync frontend/search-webapp s3://search-webapp-codepipeline